version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/DOBIZ
    ports:
      - 8000:8000
    image: app:DOBIZINDIA
    container_name: dobiz_CONTAINER
    command: python manage.py runserver 0.0.0.0:8000
