# Generated by Django 4.1.7 on 2023-03-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('timestap', models.DateTimeField(blank=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('colorcode1', models.CharField(blank=True, default='#90cd26', max_length=200, null=True)),
                ('colorcode2', models.CharField(blank=True, default='#1742fd', max_length=200, null=True)),
            ],
        ),
    ]
