# Generated by Django 4.1.7 on 2023-04-10 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dobizblog', '0004_rename_category_blogpage_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dobizblog.blogpage'),
        ),
    ]
