# Generated by Django 4.1.7 on 2023-04-24 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dobizhire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=200, null=True)),
                ('lname', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='')),
                ('msg', models.TextField(blank=True, null=True)),
                ('jobrole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dobizhire.hiredetails')),
            ],
        ),
    ]
