# Generated by Django 4.1.7 on 2023-04-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobizhire', '0003_rename_applyjobs_appliedforjobs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedforjobs',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
