# Generated by Django 4.1.7 on 2023-04-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobizhire', '0004_appliedforjobs_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedforjobs',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='CV'),
        ),
    ]
