# Generated by Django 4.1.7 on 2023-04-25 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dobizhire', '0005_alter_appliedforjobs_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedforjobs',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appliedforjobs',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appliedforjobs',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appliedforjobs',
            name='files',
            field=models.FileField(max_length=500, null=True, upload_to='CV-Resumes/'),
        ),
        migrations.AlterField(
            model_name='appliedforjobs',
            name='fname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appliedforjobs',
            name='jobrole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dobizhire.postjobs'),
        ),
        migrations.AlterField(
            model_name='appliedforjobs',
            name='lname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appliedforjobs',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
