# Generated by Django 4.2 on 2023-05-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobizhire', '0006_alter_appliedforjobs_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjobs',
            name='total_openings',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
