# Generated by Django 4.1.3 on 2023-01-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobiz', '0002_user_is_verified_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_for_forgot_pass',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
