# Generated by Django 4.1.3 on 2023-01-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobiz', '0006_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gst',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gst_percent',
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='other_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Dobiz_India_Filings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
