# Generated by Django 4.1.3 on 2023-01-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobiz', '0008_user_refer_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refer_by',
            field=models.EmailField(default='admin@dobiz.com', max_length=111),
        ),
    ]
