# Generated by Django 4.1.3 on 2023-01-28 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dobiz', '0010_alter_user_refer_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupan', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('active', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='coupan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dobiz.coupan'),
        ),
    ]
