# Generated by Django 4.1.5 on 2023-03-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobiz', '0012_order_sell_price_alter_coupan_coupan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_for_mobile',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
