# Generated by Django 4.1.5 on 2023-03-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dobiz', '0018_pricingsum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricingsum',
            old_name='save',
            new_name='yoursave',
        ),
        migrations.RenameField(
            model_name='pricingsum',
            old_name='save_value',
            new_name='yoursave_value',
        ),
    ]
