# Generated by Django 4.1.5 on 2023-03-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobiz', '0019_rename_save_pricingsum_yoursave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='heading_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='heading_text2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='list1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='list10',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='list2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='list3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='list4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='list5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='list6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='list7',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='list8',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='list9',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
