# Generated by Django 4.1.5 on 2023-03-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobiz', '0020_faq_heading_text_faq_heading_text2_faq_list1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='text2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
