# Generated by Django 4.1.5 on 2023-03-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobiz', '0022_benefits_list11_benefits_list12_benefits_list13_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequired',
            name='list21',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documentrequired',
            name='list22',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documentrequired',
            name='list23',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documentrequired',
            name='list24',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documentrequired',
            name='list25',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documentrequired',
            name='list26',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documentrequired',
            name='list27',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documentrequired',
            name='list28',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documentrequired',
            name='list29',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documentrequired',
            name='list30',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documentrequired',
            name='list31',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documentrequired',
            name='list32',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documentrequired',
            name='list33',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documentrequired',
            name='list34',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='documentrequired',
            name='list35',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
