# Generated by Django 4.1.5 on 2023-03-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobiz', '0024_documentrequired_list36_documentrequired_list37_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='list1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='list10',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='list2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='list3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='list4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='list5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='list6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='list7',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='list8',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='list9',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
