# Generated by Django 4.1.5 on 2023-03-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobiz', '0027_minimumrequirement_list11_minimumrequirement_list12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='answer10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='answer8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='answer9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='step10',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='step8',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='step9',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
