# Generated by Django 4.1.5 on 2023-03-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobiz', '0028_stepwiseprocedure_answer10_stepwiseprocedure_answer8_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minimumrequirement',
            name='list14',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='minimumrequirement',
            name='list15',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
