# Generated by Django 4.1.5 on 2023-03-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobiz', '0029_minimumrequirement_list14_minimumrequirement_list15'),
    ]

    operations = [
        migrations.AddField(
            model_name='meaning',
            name='heading_text5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='meaning',
            name='heading_text6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='meaning',
            name='heading_text7',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='meaning',
            name='heading_text8',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='meaning',
            name='heading_text9',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='meaning',
            name='list11',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='meaning',
            name='list12',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='meaning',
            name='list13',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='meaning',
            name='list14',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='meaning',
            name='text7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meaning',
            name='text8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meaning',
            name='text9',
            field=models.TextField(blank=True, null=True),
        ),
    ]
