# Generated by Django 4.1.5 on 2023-03-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobiz', '0030_meaning_heading_text5_meaning_heading_text6_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='list11',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='list12',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='list13',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='list14',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='list15',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='list16',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='list17',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='list18',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='list19',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='list20',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='list21',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='list22',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='list23',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='list24',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stepwiseprocedure',
            name='list25',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
