# Generated by Django 4.1.7 on 2023-03-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobiz', '0031_stepwiseprocedure_list11_stepwiseprocedure_list12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razor_pay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razor_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razor_payment_signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
