# Generated by Django 4.1.7 on 2023-03-20 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dobiz', '0032_order_razor_pay_order_id_order_razor_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupan',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupan',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
