# Generated by Django 4.1.7 on 2023-03-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobiz', '0033_coupan_percentage_coupan_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
