# Generated by Django 4.1.7 on 2023-03-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobiz', '0035_rename_address_line_1_order_address1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.AlterField(
            model_name='coupan',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
