# Generated by Django 4.1.7 on 2023-03-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobiz', '0036_remove_order_phone_alter_coupan_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupan',
            name='commissionpaid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
