# Generated by Django 4.1.7 on 2023-04-04 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dobiz', '0038_page_banner_page_benefits_page_closure_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dobiz.page'),
        ),
    ]
