# Generated by Django 4.1.7 on 2023-04-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobiz', '0039_product_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='section',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
