# Generated by Django 4.1.7 on 2023-04-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobiz', '0041_alter_order_product_alter_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='/static/images/common_img.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='is_packed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
