# Generated by Django 4.1.7 on 2023-04-20 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dobiz', '0042_product_img1_product_is_packed'),
        ('dobiz', '0042_product_img_product_is_packed'),
    ]

    operations = [
    ]
