# Generated by Django 4.1.7 on 2023-04-20 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dobiz', '0043_merge_20230420_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
    ]
