# Generated by Django 4.1.7 on 2023-04-20 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dobiz', '0044_remove_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dobiz.coupan'),
        ),
    ]
