# Generated by Django 4.1.7 on 2023-04-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobiz', '0046_alter_order_coupan_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
