# Generated by Django 4.2 on 2023-04-28 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dobiz', '0050_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_packed',
            new_name='is_package',
        ),
    ]
