# Generated by Django 4.2 on 2023-05-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobiz', '0052_product_discounted_percentage_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='estimated_delivery_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
